const V1 = '';

export const ENDPOINTS = {
  auth: {
    login: `${V1}/auth/login`,
    refresh: `${V1}/auth/refresh`,
    logout: `${V1}/auth/logout`,
    signup: `${V1}/auth/signup`,
    verifyEmail: `${V1}/auth/verify-email`,
    forgotPassword: `${V1}/auth/forgot-password`,
    resetPassword: `${V1}/auth/reset-password`,
    changePassword: `${V1}/me/change-password`,
  },
  me: {
    profile: `${V1}/me`,
    updateProfile: `${V1}/me`,
    menus: `${V1}/me/menus`,
  },
  users: {
    list: `${V1}/users`,
    detail: (id: number) => `${V1}/users/${id}`,
    activate: (id: number) => `${V1}/users/${id}/activate`,
    suspend: (id: number) => `${V1}/users/${id}/suspend`,
    resetPassword: (id: number) => `${V1}/users/${id}/reset-password`,
  },
  companies: {
    list: `${V1}/companies`,
    detail: (id: number) => `${V1}/companies/${id}`,
    onboardingMaster: (id: number) => `${V1}/companies/${id}/onboarding-master`,
    activate: (id: number) => `${V1}/companies/${id}/activate`,
    suspend: (id: number) => `${V1}/companies/${id}/suspend`,
    contacts: (companyId: number) => `${V1}/companies/${companyId}/contacts`,
    deleteContact: (contactId: number) => `${V1}/companies/contacts/${contactId}`,
    import: `${V1}/companies/import`,
  },
  powerStations: {
    list: `${V1}/power-stations`,
    detail: (id: number) => `${V1}/power-stations/${id}`,
    byCompany: (companyId: number) => `${V1}/power-stations/by-company/${companyId}`,
    activate: (id: number) => `${V1}/power-stations/${id}/activate`,
    deactivate: (id: number) => `${V1}/power-stations/${id}/deactivate`,
    equipment: (id: number) => `${V1}/power-stations/${id}/equipment`,
    documents: (stationId: number) => `${V1}/power-stations/${stationId}/documents`,
    deleteDocument: (docId: number) => `${V1}/power-stations/documents/${docId}`,
  },
  equipment: {
    list: `${V1}/equipment`,
    detail: (id: number) => `${V1}/equipment/${id}`,
    activate: (id: number) => `${V1}/equipment/${id}/activate`,
    deactivate: (id: number) => `${V1}/equipment/${id}/deactivate`,
    maintenances: (equipmentId: number) => `${V1}/equipment/${equipmentId}/maintenances`,
    metrics: `${V1}/equipment/metrics`,
  },
  readings: {
    byEquipment: (equipmentId: number) => `${V1}/readings/equipment/${equipmentId}`,
    create: `${V1}/readings`,
    batch: `${V1}/readings/batch`,
    dailySummary: (powerStationId: number) => `${V1}/readings/daily-summary/${powerStationId}`,
    reportSummary: `${V1}/readings/report-summary`,
  },
  anomalies: {
    list: `${V1}/anomalies`,
    detections: `${V1}/anomalies/detections`,
    detectionsUnresolved: `${V1}/anomalies/detections/unresolved`,
    resolveDetection: (id: number) => `${V1}/anomalies/detections/${id}/resolve`,
  },
  notifications: {
    list: `${V1}/notifications`,
    unreadCount: `${V1}/notifications/unread-count`,
    markRead: (id: number) => `${V1}/notifications/${id}/read`,
    markAllRead: `${V1}/notifications/read-all`,
    settings: `${V1}/notifications/settings`,
  },
  consultations: {
    list: `${V1}/consultations`,
    detail: (id: number) => `${V1}/consultations/${id}`,
    byCompany: (companyId: number) => `${V1}/consultations/by-company/${companyId}`,
    byCompanyDomain: (companyId: number, domain: string) =>
      `${V1}/consultations/by-company/${companyId}?domain=${domain}`,
    byConsultant: (consultantId: number) => `${V1}/consultations/by-consultant/${consultantId}`,
    assign: (id: number) => `${V1}/consultations/${id}/assign`,
    complete: (id: number) => `${V1}/consultations/${id}/complete`,
    cancel: (id: number) => `${V1}/consultations/${id}/cancel`,
    milestones: (id: number) => `${V1}/consultations/${id}/milestones`,
    startMilestone: (milestoneId: number) => `${V1}/consultations/milestones/${milestoneId}/start`,
    completeMilestone: (milestoneId: number) =>
      `${V1}/consultations/milestones/${milestoneId}/complete`,
    review: (id: number) => `${V1}/consultations/${id}/review`,
    diagnoses: `${V1}/consultations/diagnoses`,
    diagnosisDetail: (id: number) => `${V1}/consultations/diagnoses/${id}`,
    diagnosesByCompany: (companyId: number) =>
      `${V1}/consultations/diagnoses/by-company/${companyId}`,
    diagnosesByCompanyDomain: (companyId: number, domain: string) =>
      `${V1}/consultations/diagnoses/by-company/${companyId}?domain=${domain}`,
    recentDiagnoses: (companyId: number) => `${V1}/consultations/diagnoses/recent/${companyId}`,
    recentEnergyData: (companyId: number) =>
      `${V1}/consultations/diagnoses/recent-data/${companyId}`,
    profiles: `${V1}/consultations/profiles`,
    profileDetail: (id: number) => `${V1}/consultations/profiles/${id}`,
    profileByUser: (userId: number) => `${V1}/consultations/profiles/by-user/${userId}`,
    proposals: (consultationId: number) => `${V1}/consultations/${consultationId}/proposals`,
    acceptProposal: (proposalId: number) => `${V1}/consultations/proposals/${proposalId}/accept`,
    reports: (id: number) => `${V1}/consultations/${id}/reports`,
    approveReport: (reportId: number) => `${V1}/consultations/reports/${reportId}/approve`,
    requestReviewReport: (reportId: number) =>
      `${V1}/consultations/reports/${reportId}/request-review`,
    rejectReport: (reportId: number) => `${V1}/consultations/reports/${reportId}/reject`,
    reportComments: (reportId: number) => `${V1}/consultations/reports/${reportId}/comments`,
    settlements: (consultationId: number) => `${V1}/consultations/${consultationId}/settlements`,
    approveSettlement: (settlementId: number) =>
      `${V1}/consultations/settlements/${settlementId}/approve`,
    paySettlement: (settlementId: number) => `${V1}/consultations/settlements/${settlementId}/pay`,
    issueInvoice: (settlementId: number) =>
      `${V1}/consultations/settlements/${settlementId}/issue-invoice`,
    certifications: (profileId: number) =>
      `${V1}/consultations/profiles/${profileId}/certifications`,
    specializations: (profileId: number) =>
      `${V1}/consultations/profiles/${profileId}/specializations`,
    sites: (consultationId: number) => `${V1}/consultations/${consultationId}/sites`,
    deleteSite: (siteId: number) => `${V1}/consultations/sites/${siteId}`,
    revisions: (consultationId: number) => `${V1}/consultations/${consultationId}/revisions`,
    schedules: (consultationId: number) => `${V1}/consultations/${consultationId}/schedules`,
    confirmSchedule: (scheduleId: number) => `${V1}/consultations/schedules/${scheduleId}/confirm`,
    cancelSchedule: (scheduleId: number) => `${V1}/consultations/schedules/${scheduleId}/cancel`,
    respondSchedule: (scheduleId: number) => `${V1}/consultations/schedules/${scheduleId}/respond`,
    pendingSchedules: (companyId: number) => `${V1}/consultations/schedules/pending/${companyId}`,
    schedulesByConsultant: (consultantId: number) =>
      `${V1}/consultations/schedules/by-consultant/${consultantId}`,
    survey: (id: number) => `${V1}/consultations/${id}/survey`,
    createSurvey: (id: number) => `${V1}/consultations/${id}/survey`,
    transitionStatus: (id: number) => `${V1}/consultations/${id}/status`,
    createMilestone: (id: number) => `${V1}/consultations/${id}/milestones`,
    createProposal: `${V1}/consultations/proposals`,
    proposalsByProfile: (profileId: number) =>
      `${V1}/consultations/proposals/by-profile/${profileId}`,
    proposalsByCompany: (companyId: number) =>
      `${V1}/consultations/proposals/by-company/${companyId}`,
    updateProposal: (proposalId: number) => `${V1}/consultations/proposals/${proposalId}`,
    declineProposal: (proposalId: number) => `${V1}/consultations/proposals/${proposalId}/decline`,
    createSettlement: (id: number) => `${V1}/consultations/${id}/settlements`,
    updateProfile: (profileId: number) => `${V1}/consultations/profiles/${profileId}`,
    referralsByProfile: (profileId: number) =>
      `${V1}/consultations/referrals/by-profile/${profileId}`,
    createReferral: `${V1}/consultations/referrals`,
    acceptReferral: (referralId: number) => `${V1}/consultations/referrals/${referralId}/accept`,
    referralAnalytics: `${V1}/consultations/referrals/analytics`,
    settlementsByConsultant: (consultantId: number) =>
      `${V1}/consultations/settlements/by-consultant/${consultantId}`,
    chat: (consultationId: number) => `${V1}/consultations/${consultationId}/chat`,
    spcReviewReport: (reportId: number) => `${V1}/consultations/reports/${reportId}/spc-review`,
    spcApproveReport: (reportId: number) => `${V1}/consultations/reports/${reportId}/spc-approve`,
    recommendProfiles: `${V1}/consultations/profiles/recommend`,
    tradingRequests: (consultationId: number) =>
      `${V1}/consultations/${consultationId}/trading-requests`,
  },
  files: {
    upload: `${V1}/files`,
    download: (id: number) => `${V1}/files/${id}/download`,
    detail: (id: number) => `${V1}/files/${id}`,
  },
  codes: {
    groups: `${V1}/codes/groups`,
    groupDetail: (code: string) => `${V1}/codes/groups/${code}`,
    byGroup: (groupCode: string) => `${V1}/codes/groups/${groupCode}/codes`,
  },
  roles: {
    list: `${V1}/roles`,
    detail: (id: number) => `${V1}/roles/${id}`,
    assign: `${V1}/roles/assign`,
    revoke: `${V1}/roles/revoke`,
    assignByCode: `${V1}/roles/assign-by-code`,
    revokeByCode: `${V1}/roles/revoke-by-code`,
    menus: (roleId: number) => `${V1}/roles/${roleId}/menus`,
    revokeMenu: (roleId: number, menuId: number) => `${V1}/roles/${roleId}/menus/${menuId}`,
  },
  menus: {
    list: `${V1}/menus`,
  },
  auditLogs: {
    list: `${V1}/audit-logs`,
  },
  systemSettings: {
    list: `${V1}/settings`,
    byKey: (key: string) => `${V1}/settings/${key}`,
    billingRates: `${V1}/settings/public/billing-rates`,
    energy: `${V1}/settings/public/energy`,
  },
  monitoring: {
    dashboard: `${V1}/monitoring/dashboard`,
    plants: `${V1}/monitoring/map/plants`,
    consumers: `${V1}/monitoring/map/consumers`,
    contracts: `${V1}/monitoring/map/contracts`,
    anomalies: `${V1}/anomalies`,
    anomalyDetail: (id: number) => `${V1}/anomalies/${id}`,
    anomalyImpact: (id: number) => `${V1}/anomalies/${id}/impact`,
    plantDetail: (id: number) => `${V1}/monitoring/plants/${id}`,
    plantHistory: (id: number) => `${V1}/monitoring/plants/${id}/history`,
    plantDailySummary: (id: number) => `${V1}/monitoring/plants/${id}/daily-summary`,
    plantPerformance: (id: number) => `${V1}/monitoring/plants/${id}/performance`,
    plantsCompare: `${V1}/monitoring/plants/compare`,
    consumerDetail: (id: number) => `${V1}/monitoring/consumers/${id}`,
    consumerSupplyImpact: (companyId: number) =>
      `${V1}/monitoring/consumers/${companyId}/supply-impact`,
    consumerSupplyDemand: (companyId: number) =>
      `${V1}/monitoring/consumers/${companyId}/supply-demand`,
  },
  operator: {
    anomalies: `${V1}/operator/anomalies`,
  },
  ppa: {
    contracts: `${V1}/ppa/contracts`,
    contractDetail: (id: number) => `${V1}/ppa/contracts/${id}`,
    activateContract: (id: number) => `${V1}/ppa/contracts/${id}/activate`,
    terminateContract: (id: number) => `${V1}/ppa/contracts/${id}/terminate`,
    contractChanges: (contractId: number) => `${V1}/ppa/contracts/${contractId}/changes`,
    changesSearch: `${V1}/ppa/changes`,
    contractDocuments: (contractId: number) => `${V1}/ppa/contracts/${contractId}/documents`,
    contractDeviations: (contractId: number) => `${V1}/ppa/contracts/${contractId}/deviations`,
    changeDetail: (changeId: number) => `${V1}/ppa/changes/${changeId}`,
    approveChange: (changeId: number) => `${V1}/ppa/changes/${changeId}/approve`,
    rejectChange: (changeId: number) => `${V1}/ppa/changes/${changeId}/reject`,
    cancelChange: (changeId: number) => `${V1}/ppa/changes/${changeId}/cancel`,
    requestGeneratorApproval: (changeId: number) =>
      `${V1}/ppa/changes/${changeId}/request-generator-approval`,
    generatorApproveChange: (changeId: number) => `${V1}/ppa/changes/${changeId}/generator-approve`,
    generatorRejectChange: (changeId: number) => `${V1}/ppa/changes/${changeId}/generator-reject`,
    settlements: `${V1}/ppa/settlements`,
    settlementDetail: (id: number) => `${V1}/ppa/settlements/${id}`,
    confirmSettlement: (id: number) => `${V1}/ppa/settlements/${id}/confirm`,
    disputeSettlement: (id: number) => `${V1}/ppa/settlements/${id}/dispute`,
    startReviewSettlement: (id: number) => `${V1}/ppa/settlements/${id}/start-review`,
    adjustSettlement: (id: number) => `${V1}/ppa/settlements/${id}/adjust`,
    reconfirmSettlement: (id: number) => `${V1}/ppa/settlements/${id}/reconfirm`,
    invoices: (settlementId: number) => `${V1}/ppa/settlements/${settlementId}/invoices`,
    issueInvoice: (id: number) => `${V1}/ppa/invoices/${id}/issue`,
    payInvoice: (id: number) => `${V1}/ppa/invoices/${id}/pay`,
    invoicePdf: (id: number) => `${V1}/ppa/invoices/${id}/pdf`,
    // PPA(태양광) 수익배분 — SPC·수령계좌·배분 (설계문서 25 §3). PpaDistributionController.
    spcList: `${V1}/ppa/spc`,
    spcCreate: `${V1}/ppa/spc`,
    payoutAccounts: `${V1}/ppa/payout-accounts`,
    distribution: `${V1}/ppa/distribution`,
    allocate: (id: number) => `${V1}/ppa/settlements/${id}/allocate`,
    payDistribution: (id: number) => `${V1}/ppa/settlements/${id}/pay`,
  },
  carbon: {
    reduction: `${V1}/carbon/reduction`,
  },
  lease: {
    activities: `${V1}/lease/activities`,
    volume: `${V1}/lease/volume`,
    volumeDetail: (id: number) => `${V1}/lease/volume/${id}`,
    terminateVolume: (id: number) => `${V1}/lease/volume/${id}/terminate`,
    requestTerminationVolume: (id: number) => `${V1}/lease/volume/${id}/request-termination`,
    savings: `${V1}/lease/savings`,
    savingsDetail: (id: number) => `${V1}/lease/savings/${id}`,
    terminateSavings: (id: number) => `${V1}/lease/savings/${id}/terminate`,
    requestTerminationSavings: (id: number) => `${V1}/lease/savings/${id}/request-termination`,
    monthlyRecords: `${V1}/lease/monthly-records`,
    allMonthlyRecords: `${V1}/lease/monthly-records/all`,
    invoices: `${V1}/lease/invoices`,
    allInvoices: `${V1}/lease/invoices/all`,
    issueInvoice: (id: number) => `${V1}/lease/invoices/${id}/issue`,
    payInvoice: (id: number) => `${V1}/lease/invoices/${id}/pay`,
    disputeInvoice: (id: number) => `${V1}/lease/invoices/${id}/dispute`,
    invoicePdf: (id: number) => `${V1}/lease/invoices/${id}/pdf`,
    contractPdf: (id: number) => `${V1}/lease/volume/${id}/pdf`,
    calculateSavings: `${V1}/lease/savings/calculate`,
    requests: `${V1}/lease/requests`,
    acceptRequest: (id: number) => `${V1}/lease/requests/${id}/accept`,
    equipments: `${V1}/lease/equipments`,
    myEquipments: `${V1}/lease/equipments/my`,
    recoveries: `${V1}/lease/recoveries`,
    scheduleRecovery: (id: number) => `${V1}/lease/recoveries/${id}/schedule`,
    completeRecovery: (id: number) => `${V1}/lease/recoveries/${id}/complete`,
  },
  re100: {
    roadmap: (companyId: number) => `${V1}/re100/roadmap/${companyId}`,
    createRoadmap: `${V1}/re100/roadmap`,
    updateRoadmap: (id: number) => `${V1}/re100/roadmap/${id}`,
    sourceMix: `${V1}/re100/source-mix`,
    monthlyProgress: `${V1}/re100/monthly-progress`,
    esgReportPdf: (companyId: number) => `${V1}/re100/report/${companyId}/pdf`,
    // RE100 신규 (Re100ExtController). 설계문서 17.
    rec: `${V1}/re100/rec`,
    greenPremium: `${V1}/re100/green-premium`,
    pensionMembers: `${V1}/re100/pension/members`,
    pensionPayouts: `${V1}/re100/pension/payouts`,
    payPension: (id: number) => `${V1}/re100/pension/payouts/${id}/pay`,
    certifications: `${V1}/re100/certifications`,
    educationCourses: `${V1}/re100/education/courses`,
    // V108: RE100 분기 이행 실적 (집계 입력 대기).
    quarterly: `${V1}/re100/quarterly`,
  },
  // VPP 편입 (VppController) + 운영 read-model (VppReadController, 문서 21 런타임 검증). 설계문서 17.
  vpp: {
    resources: `${V1}/vpp/resources`,
    enroll: (id: number) => `${V1}/vpp/resources/${id}/enroll`,
    // 발전소 선택 편입 (설계문서 22 §4.1) — 기존 enroll(id) 보존, 별도 추가.
    enrollStation: `${V1}/vpp/resources/enroll-station`,
    dashboard: `${V1}/vpp/dashboard`,
    forecast: `${V1}/vpp/forecast`,
    settlement: `${V1}/vpp/settlement`,
    distribution: `${V1}/vpp/distribution`,
    groups: `${V1}/vpp/groups`,
    marketPrice: `${V1}/vpp/market-price`,
    rec: `${V1}/vpp/rec`,
    reports: `${V1}/vpp/reports`,
    bidding: `${V1}/vpp/bidding`,
    // P2-1 미커버 3기능(설계문서 15). DR 원격제어·수요예측·ADMS 골격.
    demandForecast: `${V1}/vpp/demand-forecast`,
    demandForecastSummary: `${V1}/vpp/demand-forecast/summary`,
    drResources: `${V1}/vpp/dr/resources`,
    drDispatch: `${V1}/vpp/dr/dispatch`,
    drEvents: `${V1}/vpp/dr/events`,
    drVerify: (id: number) => `${V1}/vpp/dr/events/${id}/verify`,
    admsTopology: `${V1}/vpp/adms/topology`,
    admsMeasurements: `${V1}/vpp/adms/measurements`,
  },
  // 분산에너지 효율화 (MixSimulationController). 설계문서 21.
  der: {
    mixSimulation: `${V1}/der/mix-simulation`,
  },
  // 통합관제 (ControlController). 설계문서 17.
  control: {
    sopEvents: `${V1}/control/sop-events`,
    predictAssets: `${V1}/control/predict/assets`,
    predictSignals: `${V1}/control/predict/signals`,
    safetyAlerts: `${V1}/control/safety/alerts`,
    safetyItems: `${V1}/control/safety/items`,
    inspections: `${V1}/control/safety/inspections`,
    sopScenarios: `${V1}/control/sop-scenarios`,
    safetyMap: `${V1}/control/safety/map`,
    safetyRules: `${V1}/control/safety/rules`,
    sopAdvance: (id: number) => `${V1}/control/sop-events/${id}/advance`,
    sopClose: (id: number) => `${V1}/control/sop-events/${id}/close`,
    // V105: SOP 조치 이력 / V107: 예지보전 실시간 계측.
    sopActions: (id: number) => `${V1}/control/sop-events/${id}/actions`,
    predictReadings: (assetId: number) => `${V1}/control/predict/assets/${assetId}/readings`,
  },
  trading: {
    requests: `${V1}/trading/requests`,
    requestDetail: (id: number) => `${V1}/trading/requests/${id}`,
    updateRequestStatus: (id: number) => `${V1}/trading/requests/${id}/status`,
    matches: (requestId: number) => `${V1}/trading/requests/${requestId}/matches`,
    allMatches: `${V1}/trading/matches`,
    createMatch: `${V1}/trading/matches`,
    generatorAcceptMatch: (id: number) => `${V1}/trading/matches/${id}/generator-accept`,
    acceptMatch: (id: number) => `${V1}/trading/matches/${id}/accept`,
    counterMatch: (id: number) => `${V1}/trading/matches/${id}/counter`,
    chat: (requestId: number) => `${V1}/trading/requests/${requestId}/chat`,
    leaseProposal: (id: number) => `${V1}/trading/requests/${id}/lease-proposal`,
    agreeLeaseProposal: (id: number) => `${V1}/trading/requests/${id}/lease-proposal/agree`,
    leaseProposalsByGenerator: `${V1}/trading/lease-proposals`,
    declineMatch: (id: number) => `${V1}/trading/matches/${id}/decline`,
    marketPrices: `${V1}/trading/market-prices`,
    recTransactions: `${V1}/trading/rec-transactions`,
  },
  dashboard: {
    summary: `${V1}/dashboard/summary`,
    monthlySettlements: `${V1}/dashboard/monthly-settlements`,
  },
  forecasts: {
    byPlant: (plantId: number) => `${V1}/forecasts/plants/${plantId}`,
    penalties: (plantId: number) => `${V1}/forecasts/penalties/${plantId}`,
  },
  consumer: {
    sites: `${V1}/consumer/sites`,
    siteDetail: (id: number) => `${V1}/consumer/sites/${id}`,
    updateSite: (id: number) => `${V1}/consumer/sites/${id}`,
    deleteSite: (id: number) => `${V1}/consumer/sites/${id}`,
    siteUsage: (siteId: number) => `${V1}/consumer/sites/${siteId}/usage`,
    siteUsageCalculated: (siteId: number) => `${V1}/consumer/sites/${siteId}/usage/calculated`,
    siteFacilities: (siteId: number) => `${V1}/consumer/sites/${siteId}/facilities`,
    deleteFacility: (id: number) => `${V1}/consumer/facilities/${id}`,
    billing: `${V1}/consumer/billing`,
    billingPdf: (companyId: number) => `${V1}/consumer/billing/${companyId}/pdf`,
    contracts: `${V1}/consumer/contracts`,
    contractsByStation: (powerStationId: number) =>
      `${V1}/consumer/contracts/by-station/${powerStationId}`,
  },
  agencies: {
    list: `${V1}/agencies`,
    publicList: `${V1}/agencies/public`,
    detail: (id: number) => `${V1}/agencies/${id}`,
    byCompany: (companyId: number) => `${V1}/agencies/by-company/${companyId}`,
  },
  spc: {
    assets: `${V1}/spc/assets`,
    assetDetail: (id: number) => `${V1}/spc/assets/${id}`,
    tradingMonthly: `${V1}/spc/trading/monthly`,
    generationDaily: `${V1}/spc/generation/daily`,
    suppliers: `${V1}/spc/suppliers`,
    // V106: SPC 재무 실적 (입력 대기).
    finance: `${V1}/spc/finance`,
  },
  invitations: {
    list: `${V1}/invitations`,
    create: `${V1}/invitations`,
    info: `${V1}/invitations/info`,
    accept: `${V1}/invitations/accept`,
    resend: (id: number) => `${V1}/invitations/${id}/resend`,
    cancel: (id: number) => `${V1}/invitations/${id}/cancel`,
  },
  notices: {
    list: `${V1}/notices`,
    detail: (id: number) => `${V1}/notices/${id}`,
  },
  terms: {
    list: `${V1}/terms`,
    accepted: `${V1}/terms/accepted`,
    accept: (termsId: number) => `${V1}/terms/${termsId}/accept`,
    withdraw: (termsId: number) => `${V1}/terms/${termsId}/withdraw`,
  },
  onboarding: {
    list: `${V1}/onboarding`,
    reviewQueue: `${V1}/onboarding/review-queue`,
    detail: (id: number) => `${V1}/onboarding/${id}`,
    start: `${V1}/onboarding`,
    submitStep: (stepId: number) => `${V1}/onboarding/steps/${stepId}/submit`,
    approveStep: (stepId: number) => `${V1}/onboarding/steps/${stepId}/approve`,
    rejectStep: (stepId: number) => `${V1}/onboarding/steps/${stepId}/reject`,
    complete: (id: number) => `${V1}/onboarding/${id}/complete`,
  },
  etm: {
    availablePlants: `${V1}/etm/available-plants`,
    contracts: `${V1}/etm/contracts`,
    contractDetail: (id: number) => `${V1}/etm/contracts/${id}`,
    marketPrice: `${V1}/etm/market-price`,
    settlements: `${V1}/etm/settlements`,
    invoices: `${V1}/etm/invoices`,
    invoiceDetail: (id: number) => `${V1}/etm/invoices/${id}`,
    rec: `${V1}/etm/rec`,
    recTransactions: `${V1}/etm/rec/transactions`,
    transactions: `${V1}/etm/transactions`,
  },
  signatures: {
    list: `${V1}/signatures`,
    sign: `${V1}/signatures`,
    status: `${V1}/signatures/status`,
  },
} as const;
